export const CLEAR_ERRORS ='CLEAR_ERRORS'

export const CONTACT_USER_REQUEST ='CONTACT_USER_REQUEST'
export const CONTACT_USER_SUCCESS ='CONTACT_USER_SUCCESS'
export const CONTACT_USER_FAIL ='CONTACT_USER_FAIL'